#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ronn
Version  : 0.7.3
Release  : 6
URL      : https://rubygems.org/downloads/ronn-0.7.3.gem
Source0  : https://rubygems.org/downloads/ronn-0.7.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-ronn-bin
BuildRequires : ruby
BuildRequires : rubygem-hpricot
BuildRequires : rubygem-minitest
BuildRequires : rubygem-mustache
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdiscount
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
# Ronn
Ronn builds manuals. It converts simple, human readable textfiles to roff for
terminal display, and also to HTML for the web.

%package bin
Summary: bin components for the rubygem-ronn package.
Group: Binaries

%description bin
bin components for the rubygem-ronn package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ronn-0.7.3
gem spec %{SOURCE0} -l --ruby > rubygem-ronn.gemspec

%build
gem build rubygem-ronn.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ronn-0.7.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/ronn-0.7.3 && rake -v test && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ronn-0.7.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/AUTHORS
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/CHANGES
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/INSTALLING
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/README.md
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/bin/ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/config.ru
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn.rb
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/document.rb
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/index.rb
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/roff.rb
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/server.rb
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/template.rb
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/template/80c.css
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/template/dark.css
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/template/darktoc.css
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/template/default.html
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/template/man.css
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/template/print.css
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/template/screen.css
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/template/toc.css
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/lib/ronn/utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/man/index.html
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/man/index.txt
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/man/ronn-format.7
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/man/ronn-format.7.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/man/ronn.1
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/man/ronn.1.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/ronn.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/angle_bracket_syntax.html
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/angle_bracket_syntax.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/basic_document.html
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/basic_document.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/contest.rb
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/custom_title_document.html
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/custom_title_document.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/definition_list_syntax.html
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/definition_list_syntax.roff
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/definition_list_syntax.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/dots_at_line_start_test.roff
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/dots_at_line_start_test.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/entity_encoding_test.html
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/entity_encoding_test.roff
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/entity_encoding_test.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/index.txt
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/markdown_syntax.html
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/markdown_syntax.roff
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/markdown_syntax.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/middle_paragraph.html
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/middle_paragraph.roff
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/middle_paragraph.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/missing_spaces.roff
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/missing_spaces.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/pre_block_with_quotes.roff
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/pre_block_with_quotes.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/section_reference_links.html
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/section_reference_links.roff
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/section_reference_links.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/test_ronn.rb
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/test_ronn_document.rb
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/test_ronn_index.rb
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/titleless_document.html
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/titleless_document.ronn
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/underline_spacing_test.roff
/usr/lib64/ruby/gems/2.3.0/gems/ronn-0.7.3/test/underline_spacing_test.ronn
/usr/lib64/ruby/gems/2.3.0/specifications/ronn-0.7.3.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/ronn
