#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ronn
Version  : 0.7.3
Release  : 5
URL      : https://rubygems.org/downloads/ronn-0.7.3.gem
Source0  : https://rubygems.org/downloads/ronn-0.7.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-ronn-bin
BuildRequires : ruby
BuildRequires : rubygem-hpricot
BuildRequires : rubygem-minitest
BuildRequires : rubygem-mustache
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdiscount
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
# Ronn
Ronn builds manuals. It converts simple, human readable textfiles to roff for
terminal display, and also to HTML for the web.

%package bin
Summary: bin components for the rubygem-ronn package.
Group: Binaries

%description bin
bin components for the rubygem-ronn package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ronn-0.7.3
gem spec %{SOURCE0} -l --ruby > rubygem-ronn.gemspec

%build
gem build rubygem-ronn.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ronn-0.7.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/ronn-0.7.3 && rake -v test && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/ronn-0.7.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/basename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/date-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/html_filter_angle_quotes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/html_filter_annotate_bare_links-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/html_filter_definition_lists-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/html_filter_heading_anchors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/html_filter_inject_name_section-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/html_filter_manual_reference_links-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/input_html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/manual-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/markdown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/markdown_filter_angle_quotes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/markdown_filter_heading_anchors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/markdown_filter_link_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/name%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/organization-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/path_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/path_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/path_section-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/preprocess%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/process_html%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/process_markdown%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/reference_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/section%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/section-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/section_heads-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/sniff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/strip_heading-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/styles%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/styles-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/tagline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/title%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/title-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/to_h-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/to_html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/to_html_fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/to_markdown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/to_roff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/to_yaml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Document/toc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/%5b%5d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/add_manual-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/cdesc-Index.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/exist%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/first-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/index_path_for_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/last-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/manual-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/manuals-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/read%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/reference-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/references-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/relative_to_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/to_h-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Index/to_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Reference/cdesc-Reference.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Reference/location-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Reference/manual%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Reference/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Reference/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Reference/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Reference/relative%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Reference/remote%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Reference/ronn%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Reference/url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/block_filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/cdesc-RoffFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/comment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/escape-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/inline_filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/macro-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/normalize_whitespace%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/previous-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/quote-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/remove_extraneous_elements%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/title_heading-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/warn-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/RoffFilter/writeln-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Server/cdesc-Server.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Server/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Server/run-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Server/styles-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/cdesc-Template.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/custom_title%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/date-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/generator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/inline_stylesheet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/manual-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/missing_styles-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/name_and_section%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/organization-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/page_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/remote_stylesheet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/section-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/section_heads-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/style_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/style_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/styles-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/stylesheet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/stylesheet_tags-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/stylesheets-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/tagline%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/tagline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/title-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Template/wrap_class_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Utils/block_element%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Utils/cdesc-Utils.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Utils/child_of%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Utils/empty_element%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Utils/html_element%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/Utils/inline_element%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/cdesc-Ronn.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/release%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/revision-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/Ronn/version-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/lib/ronn/template/page-80c_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/lib/ronn/template/page-dark_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/lib/ronn/template/page-darktoc_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/lib/ronn/template/page-default_html.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/lib/ronn/template/page-man_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/lib/ronn/template/page-print_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/lib/ronn/template/page-screen_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/lib/ronn/template/page-toc_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/page-AUTHORS.ri
/usr/lib64/ruby/gems/2.2.0/doc/ronn-0.7.3/ri/page-COPYING.ri
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/AUTHORS
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/CHANGES
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/COPYING
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/INSTALLING
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/bin/ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/config.ru
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn.rb
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/document.rb
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/index.rb
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/roff.rb
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/server.rb
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/template.rb
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/template/80c.css
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/template/dark.css
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/template/darktoc.css
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/template/default.html
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/template/man.css
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/template/print.css
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/template/screen.css
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/template/toc.css
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/lib/ronn/utils.rb
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/man/index.html
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/man/index.txt
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/man/ronn-format.7
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/man/ronn-format.7.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/man/ronn.1
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/man/ronn.1.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/ronn.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/angle_bracket_syntax.html
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/angle_bracket_syntax.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/basic_document.html
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/basic_document.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/contest.rb
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/custom_title_document.html
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/custom_title_document.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/definition_list_syntax.html
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/definition_list_syntax.roff
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/definition_list_syntax.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/dots_at_line_start_test.roff
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/dots_at_line_start_test.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/entity_encoding_test.html
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/entity_encoding_test.roff
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/entity_encoding_test.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/index.txt
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/markdown_syntax.html
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/markdown_syntax.roff
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/markdown_syntax.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/middle_paragraph.html
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/middle_paragraph.roff
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/middle_paragraph.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/missing_spaces.roff
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/missing_spaces.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/pre_block_with_quotes.roff
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/pre_block_with_quotes.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/section_reference_links.html
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/section_reference_links.roff
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/section_reference_links.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/test_ronn.rb
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/test_ronn_document.rb
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/test_ronn_index.rb
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/titleless_document.html
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/titleless_document.ronn
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/underline_spacing_test.roff
/usr/lib64/ruby/gems/2.2.0/gems/ronn-0.7.3/test/underline_spacing_test.ronn
/usr/lib64/ruby/gems/2.2.0/specifications/ronn-0.7.3.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/ronn
